node{
    def commit_id
    stage('Preparation'){
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id"
        commit_id = readFile('.git/commit-id').trim()
    }
    stage('test') {
        nodejs(nodeJSInstallationName: 'NodeJS'){
            sh 'npm install'
            sh 'echo "done"'
        }
    }
    stage('docker build/push'){
        docker.withRegistry('registry.digitalocean.com', 'digitaldock'){
            def app = docker.build("firstnestjsdocker/firstnestjsdocker:${commit_id}", '.').push()
        }
    }
}